# Introduction to Julia

- This introduction doesn't replace a full Julia course.
- We only want to point out the basics, especially those that are different to Python.

- We have seen a very powerful usecase of Python. 
- Why would we want to use any other language?
- -> Speed

- Julia's LLVM-based JIT compiler (Low level virtual machine just-in-time) compiler combined with the language's design allows it to approach and often match the performance of C in typical user scenarios.

![](Images/benchmarks.svg)

### Some History
- started 2009 at MIT by Alan Edelman, Jeff Bezanson, Stefan Karpinski, Viral Shah
- publicly announced 2012
- v0.6 2017 Jun 19: pretty much the "modern" version of Julia
    - Some old stuff you encounter in the internet is targeted for this. So be aware!
- v0.7 2018 Aug 8: short test release before v1
- v1.0 2018 Aug 9: Official release
- v1.1 2019 Jan 22: minor improvements & bug fixes

### Syntax

In [1]:
function mandel(z)
    c = z
    maxiter = 80
    for n = 1:maxiter
        if abs(z) > 2
            return n-1
        end
        z = z^2 + c
    end
    return maxiter
end

mandel (generic function with 1 method)

In [2]:
[ mandel(complex(r,i)) for i=-1.:.2:1., r=-2.0:.2:0.5 ]

11×13 Matrix{Int64}:
  0   0   1   2   2   2   2   3   3   6  80   3   2
  0   1   2   2   2   2   3   3   5  80  17   4   3
  0   2   2   2   2   3   4  11  25  80  80  11  14
  0   2   2   4   6   6   6  80  80  80  80  80   8
  0   3   4   5  17  80  14  80  80  80  80  80  30
 80  80  80  80  80  80  80  80  80  80  80  80   6
  0   3   4   5  17  80  14  80  80  80  80  80  30
  0   2   2   4   6   6   6  80  80  80  80  80   8
  0   2   2   2   2   3   4  11  25  80  80  11  14
  0   1   2   2   2   2   3   3   5  80  17   4   3
  0   0   1   2   2   2   2   3   3   6  80   3   2

- The syntax is easy to use and learn.
- It will seem familiar to Python and Matlab users.
- It is possible to do complicated computations quickly.


For example, Solving $$Ax=b$$ with $$A = \begin{pmatrix}\,
    1 & 2 & 3\\ 
    2 & 1 & 2\\ 
    3 & 2 & 1
    \end{pmatrix}$$
    and $$b = \begin{pmatrix}
    1 \\
    1 \\ 
    1 
    \end{pmatrix}$$

In [3]:
A = [1 2 3
     2 1 2
     3 2 1]

b = [1,1,1]
A\b

3-element Vector{Float64}:
 0.25
 0.0
 0.25000000000000006

### A dynamic language:

- Julia is, like Python, Matlab or R, a dynamic language: 
    - You can interact with the language without the need to compile your code. 
    - Static or compiled languages, like C or Fortran, are more complicated to use but generally faster, and thus used when there is a need for time-efficient computations.

- This is the two-languages problem: 
    - One generally use a high level language for research and scripting, 
    - and then translate the final result in a static language for performance.

### A High Performance language:

- Julia solves the two languages problem using just-in-time compilation. 
    - While running, your code will be automatically compiled and optimized to reach performances comparable to static languages like C, Fortran and Go.
- Unlike R, Matlab or Python, simple loops are extremely efficient in Julia:

In [4]:
function countTo(n)
    count = 0
    for i = 1:n
        count += 1
    end
    return count
end
println("First use: slow like a dynamic language")
@time countTo(10_000_000)
println("Second use: compiled and optimized automatically")
@time countTo(10_000_000)
@time countTo(10_000_000)

First use: slow like a dynamic language
  0.020126 seconds
Second use: compiled and optimized automatically
  0.025451 seconds
  0.018975 seconds


10000000

### Basic usage

Julia, as a dynamic language, can simply be used as a calculator:

In [6]:
1+1

2

In [7]:
sin(exp(2*pi)+sqrt(3))

-0.01136232398070678

The building blocs of Julia code are **variables**:

In [8]:
a = 1
b = 2
# This is a comment 
c = a^2 + b^3 

9

In [46]:
😺 = "smiley cat!"
typeof(😺)

String

### Variables and data types

Julia allows to write generic code. Symbols like 😺 are an example of this.

In Julia variable names

- may contain letters, numbers, underscores or exclamation marks.
- start with a letter or underscores (but not with a number!)
- are case sensitive
- in addition, UTF-8 symbols are supported!


### Special characters

Julia supports many special characters familiar from ```LaTeX```. Just try common names such as ```\alpha``` and press ```<TAB>``` to complete.

If the name is not familiar to you, just copy the character and use the ? to probe what it is.

In [47]:
α = 0.01
β = 0.2

0.2

In [48]:
π #some are already defined, like pi

π = 3.1415926535897...

In [49]:
?γ

"γ" can be typed by \gamma<tab>

search:

Couldn't find γ
Perhaps you meant A, B, a, b, c, i, l, x, α, β, 😺, /, I, \, ×, ⋅, !, %, & or '


No documentation found.

Binding `γ` does not exist.


### Dynamic and loose

Julia is a dynamically and loosely typed language. In practise, this means that:

- variables (and their types) don't need to be declared
    - but they can be
- variables are automatically casted to "correct" types


In [50]:
a = 1
b = 3
c = a/b #what will happen?

0.3333333333333333

### Data types

**Primitive and abstract types**


- Numeric types, that represent numbers
    - Number
        - Real (example: a::Real)
        - Integer (example: b::Int)
                Int16, Int32, Int64,..., UInt64
     - AbstractFloat
          Float16, Float32,Float64,...
- Strings (String, Char,...)
- Bool is a data type that can be either true or false.


**Composite types**


- complex (Complex{Int64},...) with 1 + 0.1im
- Arrays (Array{Int64,1},...)
- Mappings
    - Dict: a dictionary, also called a hashmap (Dict{String,Int64},...)


### Numeric literal coefficients

To make common formulas and expressions more clear, Julia allows variables to be immediately preceded by a number, implying multiplication.

This makes writing polynomial expressions much cleaner:

In [51]:
x = 3
2x^2 - 3.5x + 1

8.5

In [52]:
2(x-1)^2 - 3(x-1) + 1

3

### Arrays

Arrays are created using the ```[]``` brackets (or the ```Array``` constructor.)

Arrays support multiple types of indexing with normal indices and with range operator ```:```.

In [54]:
arr = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [55]:
arr[1]   # indexing starts from 1

1

In [56]:
arr[1:3] # so-called slice syntax can be used to select parts of an array

3-element Vector{Int64}:
 1
 2
 3

In [57]:
arr[end] # end keyword points to the end of the array

4

Type can be specifically forced by writing them in front of the array brackets:

In [58]:
arr = Float64[1,2,3,4]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

Arrays can be extended with several methods.

In [59]:
arr = [1, 2]

2-element Vector{Int64}:
 1
 2

In [60]:
push!(arr, 3) # Exclamation mark ! means that the function mutates its argument

3-element Vector{Int64}:
 1
 2
 3

In [61]:
insert!(arr, 1, 42) # insert places the given element to given location in the array

4-element Vector{Int64}:
 42
  1
  2
  3

In [62]:
append!(arr, [100, 101, 102]) # append another array to the end

7-element Vector{Int64}:
  42
   1
   2
   3
 100
 101
 102

**2D Arrays**

In [63]:
matrix = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

**N-dimensional Arrays**

For more dimensions than 2, one should initialize the arrays somehow else.

Standard ways are:

In [64]:
A = zeros(3,3,3)

3×3×3 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [65]:
B = ones(4,5,6,7)

4×5×6×7 Array{Float64, 4}:
[:, :, 1, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 2, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 3, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 4, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 5, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 6, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 1, 2] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 2, 2] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 3, 2] =
 1.0  1.0  1.0  1.0  1.0
 1.0 

In [66]:
C = rand(2,3,4,5,6)

2×3×4×5×6 Array{Float64, 5}:
[:, :, 1, 1, 1] =
 0.626403  0.537873  0.924301
 0.656116  0.364871  0.186408

[:, :, 2, 1, 1] =
 0.399052  0.462579  0.624574
 0.539237  0.646921  0.983698

[:, :, 3, 1, 1] =
 0.640139  0.512163  0.26524
 0.45682   0.350083  0.856136

[:, :, 4, 1, 1] =
 0.855976  0.23205   0.429975
 0.373379  0.843202  0.309599

[:, :, 1, 2, 1] =
 0.233395  0.952064  0.951838
 0.416192  0.182916  0.307025

[:, :, 2, 2, 1] =
 0.789561  0.566991  0.806427
 0.85196   0.440878  0.0513769

[:, :, 3, 2, 1] =
 0.538769  0.0649833  0.228968
 0.195866  0.0485142  0.906979

[:, :, 4, 2, 1] =
 0.569613  0.514444  0.458406
 0.982521  0.786136  0.347724

[:, :, 1, 3, 1] =
 0.853175  0.15487   0.284398
 0.644528  0.418822  0.506507

[:, :, 2, 3, 1] =
 0.151931  0.686132  0.768818
 0.968403  0.403597  0.218367

[:, :, 3, 3, 1] =
 0.639542  0.674058  0.0517755
 0.184218  0.134158  0.794882

[:, :, 4, 3, 1] =
 0.5401    0.883351  0.22703
 0.389115  0.43445   0.00125305

[:, :, 1, 4, 1] =
 

### Dictionaries

- If we have sets of data related to one another, we may choose to store that data in a dictionary. 
- We can create a dictionary using the ```Dict()``` function, which we can initialize as an empty dictionary or one storing key, value pairs.

Syntax:

Dict(key1 => value1, key2 => value2, ...)


In [68]:
myphonebook = Dict("George" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String, String} with 2 entries:
  "George"       => "867-5309"
  "Ghostbusters" => "555-2368"

In [69]:
myphonebook["George"] # we can access the element by using the key

"867-5309"

In [70]:
myphonebook["Kramer"] = "555-FILK" # new elements can be easily added

"555-FILK"

### Tuples

- We can create a tuple by enclosing an ordered collection of elements in ```( )```. 
    - Syntax is ```(item1, item2,...)```.

- Julia does automatic packing and unpacking of tuples as ```(a, b) = 1, 2```.

- Note that tuples are **immutable**!

In [71]:
myfavoriteanimals = ("penguins", "cats", "sugargliders")

("penguins", "cats", "sugargliders")

In [72]:
myfavoriteanimals[1] # tuples can be indexed the same way as arrays

"penguins"

In [73]:
myfavoriteanimals[1] = "otters" #but not modified since they are immutable

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

### Big numbers

Arbitrary precision arithmetics is also supported.

In [74]:
BigFloat(2.0^66) / 3

2.459565876494606882133333333333333333333333333333333333333333333333333333333344e+19

### Advanced: Dynamic types

- When evaluating ```1/3```, it equals ```0.3333...``` (which is what the user often meant). 
- However, not always! Then the ```::``` operator can be attached to the expressions. It is read as "*is instance of*".

In [80]:
a = 1
b = 3
c = (a + b)::Int
typeof(c)

Int64

In [76]:
c

4

### Control flow

Julia supports the common if, while and for structures:

In [9]:
if c >= 10
    print("Joey")
else
    print("Rachel")
end
     

Rachel

In [10]:
i = 1
while i <= 5
    println("Joey!") # Print with a new line
    i += 1
end
     

Joey!
Joey!
Joey!
Joey!
Joey!


In [11]:
for i = 1:3
    print("$i Joey") # '$' can be used to insert variables into text
    if i>1
        print("s")
    end
    println() # Just a new line
end

1 Joey
2 Joeys
3 Joeys


- Do not worry about writing loops: in Julia, they are as fast as writing vectorized code, and sometimes faster!

#### For loops for iteration

For loops can also be used to iterate over containers:

In [83]:
for i in [1,4,0]
    println(i)
end

1
4
0


In [84]:
for s ∈ ["foo","bar","baz"]
    println(s)
end

foo
bar
baz


**Ternary operator**

Even though the name for this operation is scary, it is actually very easy to understand and handy to use. Syntax is:

```condition ? do 1 : do 2```

which is equal to writing

if *condition*
   
>   *do 1*

else

>   *do 2*

end


In [82]:
# What does the followning code do? Try it out by giving values to `x` and `y`
x = 
y = 
(x > y ) ? x : y

LoadError: UndefVarError: y not defined

In [36]:
function myFunction(x)
    println("Julia!")
end

function myFunction(x::Int) # only called when x is an integer
    println("integer")
end

myFunction(1.0)
myFunction(1)
myFunction("Joey")

Julia!
integer
Julia!


A lot more functionalities are available and for you to discover!

In [37]:
l = [i^2 for i in 1:10 if i%2 == 0] # list comprehensions (similar to Python)

5-element Vector{Int64}:
   4
  16
  36
  64
 100

### Functions

Functions are the building blocks of Julia code, acting as the subroutines, procedures, blocks, and similar structural concepts found in other programming languages.

- A function's job is to take a tuple of values as an argument list and return a value.
- If the arguments contain mutable values like arrays, the array can be modified inside the function.
    - By convention, an exclamation mark (!) at the end of a function's name indicates that the function may modify its arguments.

**How to declare a function**

Julia gives us a few different ways to write a function. The first (and most standard) requires function and end keywords.

In [85]:
function sayhi(name)
    println("Hi $name, nice to meet you!")
end

sayhi("R2D2")

Hi R2D2, nice to meet you!


In [86]:
function f(x)
    return x^2
end

f(42)

1764

**Single line function definitions**

Alternatively, we could have spared a few lines of code and written:

In [87]:
sayhi2(name) = println("Hi $name, nice to meet you!")

sayhi2 (generic function with 1 method)

In [88]:
f2(x) = x^2

f2 (generic function with 1 method)

**Anonymous functions**

Or we could have declared them as "anonymous" functions as


In [90]:
sayhi3 = name -> println("Hi $name, nice to meet you!")

#7 (generic function with 1 method)

In [91]:
f3 = x -> x^2

#9 (generic function with 1 method)

**Duck-typing in Julia**

*If it quacks like a duck, it's a duck.*

- Julia functions will just work on whatever input makes sense. 
- For example, sayhi works also with the name written as an integer:


In [92]:
sayhi(55595472)

Hi 55595472, nice to meet you!


And ```f``` will work on a matrix:

In [93]:
A = rand(3,3)
A

3×3 Matrix{Float64}:
 0.881973  0.939591   0.654905
 0.337591  0.0970538  0.996315
 0.239653  0.391179   0.583737

In [94]:
f(A)

3×3 Matrix{Float64}:
 1.25202   1.17607   1.89603
 0.56928   0.716353  0.899372
 0.483319  0.491486  0.887436

**Mutating vs. non-mutating functions**

- By convention, functions followed by ```!``` alter their contents and functions lacking ! do not.

- For example, let's look at the difference between sort and sort!.


In [95]:
v = [3,5,2]

3-element Vector{Int64}:
 3
 5
 2

In [96]:
sort(v)

3-element Vector{Int64}:
 2
 3
 5

In [97]:
v

3-element Vector{Int64}:
 3
 5
 2

- ```sort(v)``` returns a sorted array that contains the same elements as ```v```, but ```v``` is left unchanged.

- On the other hand, when we run ```sort!(v)``` the content of ```v``` is really modified.


In [98]:
sort!(v)

3-element Vector{Int64}:
 2
 3
 5

In [99]:
v

3-element Vector{Int64}:
 2
 3
 5

#### Some higher-order functions: ```map```

- ```map``` is a "higher-order" function in Julia that takes a function as one of its input arguments. 
- ```map``` then applies that function to every element of the data structure you pass.

For example

```map(f, [1,2,3])```

will correspond to

```[f(1), f(2), f(3)]```



#### Some higher-order functions: ```broadcast```


- ```broadcast``` is another higher-order function like ```map```. ```broadcast``` is actually a generalization, so it can do what map but also more!

- Syntax is the same

```broadcast(f, [1,2,3])```

And so we have again applied f (squared) to all elements of [1,2,3].

#### Broadcasting (or vectorizing)

Some syntactic sugar for calling ```broadcast``` is to place ```.``` between the name of the function you want to broadcast and its input arguments.

For example

```broadcast(f, [1,2,3])```

is the same as

```f.([1,2,3])```

Note that this is not the same as ```f([1,2,3])``` because we can not square a vector!

Let's try broadcasting for a matrix ```A```:


In [100]:
A = [i + 3j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [101]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [102]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

#### Dot syntax for vectorization

The dot syntax allows to write complex compound elementwise expressions in a way that looks natural/closer to mathematical notation.

For example:

In [103]:
A + 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

Instead of the more nasty looking version with broadcast as

In [104]:
broadcast(x-> x + 2 * f(x) / x, A) 

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

### Navigating Julia

Julia has a package manager to quickly download, install, update and uninstall new tools (packages)

In [45]:
using Pkg
# Add Packages Plots, and Pyplot (can take some time)
Pkg.add("Plots")
Pkg.add("PyPlot")
# Update
Pkg.update()
#Remove:
# Pkg.rm("PyPlot")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
Precompiling project...
  ✓ GR
  ✓ Plots
  2 dependencies successfully precompiled in 139 seconds. 161 already precompiled. 1 skipped during auto due to previous errors.
  2 dependencies precompiled but different versions are currently loaded. Restart julia to access the new versions
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


Use ? to get the documentation of a function:

In [40]:
?eig

search: eigen eigmin eigmax eigen! Eigen eigvecs eigvals eigen_c eigen_b eigen_a

Couldn't find eig
Perhaps you meant big, eigen, ceil, reim, edit, exit, eof, eps, esc, exp or end


No documentation found.

Binding `eig` does not exist.


Use tab-completion to auto-complete functions and variables names: try myF<TAB>:

In [ ]:
myF
fac

The ```methods``` function lists all of the different implementations of a function depending on the input types. Click on the link to see the Julia source code.

In [41]:
methods(sin)

# 14 methods for generic function "sin":
[1] sin(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:29
[2] sin(J::UniformScaling) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/uniformscaling.jl:173
[3] sin(D::Diagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:674
[4] sin(A::Hermitian{var"#s884", S} where {var"#s884"<:Complex, S<:(AbstractMatrix{<:var"#s884"})}) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:731
[5] sin(A::Union{Hermitian{var"#s885", S}, Symmetric{var"#s885", S}} where {var"#s885"<:Real, S}) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:727
[6] sin(A::AbstractMatrix{<:Real}) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/dense.jl:948
[7] sin(A::AbstractMatrix{<:Complex}) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/dense.jl:955
[8] sin(a::Float16) in Base.Math at math.jl:1352
[9] sin(a::ComplexF16) in Base.Math at math.jl:1353
[10] sin(z::Complex{T}) where T in Base at complex.jl:873
[11] sin(::Irrational{:π}) in Base.MathConstants at mathconstants.jl:126
[12] sin(x::BigFloat) in Base.MPFR at mpfr.jl:750
[13] sin(x::Real) in Base.Math at math.jl:1369
[14] sin(::Missing) in Base.Math at math.jl:1374

### Plotting in IJulia(Jupyter)

There are several Julia plotting packages.

- ```PyPlot.jl``` is a Julia interface to Matplotlib, and should feel familiar to both MATLAB and Python users.
- ```Gadfly``` is written entirely in Julia, inspired by ggplot2, and concentrates on statistical graphics.
- ```Plotly``` supports Julia.
- ```Plots``` is a meta plotting package, that can use any other plotting package to make the same plot
And a lot more

Jupyter/IJulia will render the plots directly on the notebook!

In [44]:
using Plots
pyplot() #plot using Matplotlib
x = range(0,5,1000)
plot(x, sin(x.^2))

LoadError: MethodError: no method matching sin(::Vector{Float64})
Closest candidates are:
  sin(::T) where T<:Union{Float32, Float64} at special/trig.jl:29
  sin(::AbstractGray) at ~/.julia/packages/ColorVectorSpace/QI5vM/src/ColorVectorSpace.jl:315
  sin(::UniformScaling) at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/uniformscaling.jl:173
  ...

Note that the first plot while always take a few seconds to be drawn, a consequence of Julia's just in time compilation. Lots of other plot types are available.


### Ecosystem

- Julia has a large ecosystem of packages, maintained by a wide variety of people.

- In the best of academic ideals, Julia users from across the world come together to create mutually compatible and supporting packages for their domains. 
- To manage these collections of packages they often use ```GitHub``` organisations


#### Julia package ecosystem pulse

![](Images/juliapackageecosystem.svg)

#### General

- ```JuliaDocs``` – Documentation-related packages for Julia
- ```Julia-i18n``` – Internationalization (i18n) and localization (L10n) for Julians
- ```JuliaTime``` – Date and time libraries
- ```JuliaPraxis``` – Best practices
- ```JuliaEditorSupport``` – Extensions/Plugins for text editors and IDEs
- ```Juno``` – The Juno IDE for Atom




#### Computing

- ```JuliaArrays``` – Custom array types (and utilities for building array types)
- ```JuliaBerry``` – Julia resources for the Raspberry Pi
- ```JuliaCI``` – Continuous Integration Support for Julia packages
- ```JuliaGPU``` – GPU computing
- ```JuliaInterop``` – Easy interoperability between Julia and not-Julia
- ```JuliaIO``` – IO-related functionality, such as serialization
- ```JuliaParallel``` – Parallel programming in Julia
- ```JuliaWeb``` – Web stack



#### Mathematics

- ```JuliaDiff``` – Differentiation tools
- ```JuliaDiffEq``` – Differential equation solving and analysis
- ```JuliaGeometry``` – Computational Geometry
- ```JuliaGraphs``` – Graph Theory and Implementation
- ```JuliaIntervals``` - Rigorous numerics with interval arithmetic & applications
- ```JuliaMath``` – Mathematics made easy in Julia
- ```JuliaOpt``` – Optimization
- ```JuliaPolyhedra``` – Polyhedral computation
- ```JuliaSparse``` – Sparse matrix solvers



#### Scientific domains

- ```BioJulia``` – Biology
- ```EcoJulia``` – Ecology
- ```JuliaAstro``` – Astronomy
- ```JuliaDSP``` – Digital signal processing
- ```JuliaQuant``` – Finance
- ```JuliaQuantum``` – Julia libraries for quantum science and technology
- ```JuliaPhysics``` – Physics
- ```JuliaDynamics``` - Dynamical systems, nonlinear dynamics and chaos.



#### Data sciences

- ```JuliaML``` – Machine Learning
- ```JuliaStats``` – Statistics
- ```JuliaImages``` – Image Processing
- ```JuliaText``` – Natural Language Processing (NLP), Computational Linguistics and (textual) Information Retrieval
- ```JuliaDatabases``` – Various database drivers for Julia
- ```JuliaData``` – Data manipulation, storage, and I/O in Julia



### Writing fast code

#### Type instability

In [1]:
function pos(x)
    if x < 0
        return 0
    else
        return x
    end
end

pos (generic function with 1 method)

In [2]:
pos(1.5)

1.5

In [3]:
pos(-2.5)

0

In [7]:
typeof(pos(1.5))

Float64

In [8]:
typeof(pos(-2.5))

Int64

![](Images/uhoh.png)

- Historically important perfomance issue.
- Since version 1.0 compiler can handle simple cases of type instabilities.

In [10]:
function pos_fixed(x)
    if x < 0
        return zero(x)
    else
        return x
    end
end

pos_fixed (generic function with 1 method)

In [11]:
typeof(pos_fixed(-2.5))

Float64

Another example:

In [12]:
function sumsqrt(n)
    r = 0 
    for i = 1:n
        r = r + sqrt(i)
    end
    return r
end

sumsqrt (generic function with 1 method)

```r``` changes type within the loop (from int to float)

#### Fast function calls

- Rule of thumb: don't use **global variables**.

- Julia is fast because the compiler can make optimizations based on type inference.
- A global variable can come from anywhere and the compiler can't do any inference at compile time.

In [21]:
p = 2 # global variable

function pow_array(x::Vector{Float64})
    s = 0.0
    for y in x
        s = s + y^p
    end
    return s
end


pow_array (generic function with 1 method)

In [22]:
t = rand(10000)

@time pow_array(t)

  0.003465 seconds (30.00 k allocations: 468.750 KiB)


3294.6783779398093

In [23]:
const p = 2 # const global variable

function pow_array(x::Vector{Float64})
    s = 0.0
    for y in x
        s = s + y^p
    end
    return s
end

LoadError: cannot declare p constant; it already has a value

In [24]:
t = rand(10000)

@time pow_array(t)

  0.000891 seconds (30.00 k allocations: 468.750 KiB)


3346.7363835445003